name: "Test Suite"

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install dependencies"
        run: |
          python -m pip install tox tox-gh-actions coverage

      - name: "Run tox for ${{ matrix.python-version }}"
        run: |
          python -m tox
          export TOTAL=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
          export STMTS=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['num_statements'])")
          echo "total=$TOTAL" >> $GITHUB_ENV
          echo "stmts=$STMTS" >> $GITHUB_ENV
          echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY
          echo "#### Statements: ${STMTS}" >> $GITHUB_STEP_SUMMARY
      
      # - name: "Upload coverage data"
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: covdata
      #     path: .coverage.*
